---
items:
  bow:
    enchantments:
      - ARROW_INFINITE
      - ARROW_KNOCKBACK
    hide:
      - "false"
    levels:
      - "1"
      - "2"
    lore:
      - "§eARC"
    material: BOW
    name: "§cArc Infini"
  rod:
    enchantments:
      - ARROW_DAMAGE
    hide:
      - "true"
    levels:
      - "5"
    lore:
      - "§eROD"
    material: FISHING_ROD
    name: "§cRod Infinie"
  sword:
    enchantments:
      - DAMAGE_ALL
      - FIRE_ASPECT
    hide:
      - "false"
    levels:
      - "5"
      - "2"
    lore:
      - "§7⦁ §eRareté : §c✯✯✯✯"
      - "§7⦁ §eCette §6Epée §erevient dans"
      - "§7⦁ §el'inventaire après la mort !"
    material: DIAMOND_SWORD
    name: "§c❃ Epée Infinie ❃"
